---
dist: focal
language: python
python: "3.6.10"
sudo: required

services:
  - docker
install:
  - pip install ansible==4.10.0
  - pip install molecule==3.6.1
  - pip install molecule-docker==1.1.0
  - pip install docker
script:
  - molecule test --driver-name docker
