---

- name: FLUENTD | Install prerequisites
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes

- name: FLUENTD | Download fluent-package install script
  ansible.builtin.get_url:
    url: "{{ fluentd_install_script_url }}"
    dest: "{{ fluentd_install_script_dest }}"
    mode: '0755'
    force: true

- name: FLUENTD | Install fluent-package
  ansible.builtin.command: "{{ fluentd_install_script_dest }}"
  args:
    creates: "{{ fluentd_install_marker_path }}"
  notify: restart fluentd

- name: FLUENTD | Add fluentd user to secondary groups
  ansible.builtin.user:
    name: "{{ fluentd_user }}"
    groups: "{{ fluentd_secondary_groups }}"
    append: true
  when: fluentd_secondary_groups | length > 0
  notify: restart fluentd

- name: FLUENTD | Install fluentd plugin gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    user_install: no
    executable: "/usr/sbin/fluent-gem"
  with_items: "{{ fluentd_plugins }}"
  notify: restart fluentd
