---

- name: Install repo
  ansible.builtin.apt:
    deb: "{{ fluentd_deb_repo_url }}"
    update_cache: yes

- name: Install fluentd package
  ansible.builtin.apt:
    name: fluent-package
    update_cache: yes

- name: FLUENTD | Install fluentd plugin gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    user_install: no
    executable: "/usr/sbin/fluent-gem"
  with_items: "{{ fluentd_plugins }}"
  notify: restart fluentd