---

- name: FLUENTD | Create fluentd group
  group:
    name: "{{ fluentd_group }}"
    state: present

- name: FLUENTD | Create fluentd user
  user:
    name: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    groups: "{{ fluentd_secondary_groups }}"

- name: FLUENTD | Install required libs on Debian/Ubuntu
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: ["gcc", "make", "ruby", "ruby-dev"]
  when: (ansible_facts['distribution'] == "Debian") or (ansible_facts['distribution'] == "Ubuntu")

- name: FLUENTD | Install required libs on CentOS/Amazon
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items: ["gcc", "make", "ruby", "ruby-devel"]
  when: (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "Amazon")

- name: FLUENTD | Install fluentd gem
  gem:
    name: fluentd
    state: present
    version: "{{ fluentd_version }}"
    user_install: no
  notify: restart fluentd

- name: FLUENTD | Install fluentd plugin gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    user_install: no
  with_items: "{{ fluentd_plugins }}"
  notify: restart fluentd
