---

- name: FLUENTD | Create fluentd group
  group:
    name: "{{ fluentd_group }}"
    state: present

- name: FLUENTD | Create fluentd user
  user:
    name: "{{ fluentd_user }}"
    group: "{{ fluentd_group }}"
    groups: "{{ fluentd_secondary_groups }}"

- name: FLUENTD | Install required libs on Debian
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: ["gcc", "make", "ruby", "ruby-dev"]
  when:
    - ansible_distribution == "Debian"

- name: FLUENTD | Install required libs on Ubuntu
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: ["gcc", "make", "ruby", "ruby-dev"]
  when:
    - ansible_distribution == "Ubuntu"

- name: FLUENTD | Install required libs on Amazon
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items: ["gcc", "make", "ruby", "ruby-devel"]
  when:
    - ansible_distribution == "Amazon"

- name: FLUENTD | Install fluentd gem dependency
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: [ "ruby-ffi", "ruby-ffi-jajl", "ruby-jajl"]

- name: FLUENTD | Install fluentd gem
  gem:
    name: fluentd
    state: present
    version: "{{ fluentd_version }}"
    user_install: no
  notify: restart fluentd

- name: FLUENTD | Install fluentd plugin gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
    user_install: no
  with_items: "{{ fluentd_plugins }}"
  notify: restart fluentd
