---

- name: Install repo
  ansible.builtin.apt:
    deb: "{{ fluentd_deb_repo_url }}"
    update_cache: yes

- name: Install fluentd package
  ansible.builtin.apt:
    name: fluent-package
    update_cache: yes