---
- name: FLUENTD | Install
  include_tasks: 
    file: install.yml
    apply:
      tags:
        - install
  tags:
    - install

- name: FLUENTD | Configure
  include_tasks: 
    file: config.yml
    apply:
      tags:
        - configure
  tags:
    - configure

- name: FLUENTD | Service
  include_tasks: 
    file: service.yml
    apply:
      tags:
        - service
  tags:
    - service
