---
- name: FLUENTD | Install
  include_tasks: install.yml
  tags:
    - install

- name: FLUENTD | Configure
  include_tasks: config.yml
  tags:
    - configure

- name: FLUENTD | Service
  include_tasks: service.yml
  tags:
    - service
